ALTER TABLE collections ADD COLUMN created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW();
ALTER TABLE tasks ADD COLUMN created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW();
ALTER TABLE options ADD COLUMN created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW();